version: 4.2.{build}
image: Visual Studio 2015


clone_depth: 1


environment:
  matrix:
  - PlatformToolset: v140_xp
  - PlatformToolset: v120_xp

platform:
    - x64
    - Win32

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="Win32" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%

build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd c:\projects\NPP_ExportPlugin\vs7project\
    - msbuild NppExport.vcxproj /p:configuration="%configuration%" /p:platform="%platform%" /p:PlatformToolset="%PlatformToolset%"

after_build:
    - cd c:\projects\NPP_ExportPlugin\
    - ps: >-
        $NPP_ExportPluginFileName = "NppExport.$env:PLATFORM.$env:CONFIGURATION.$env:PLATFORMTOOLSET.dll"

        if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "vs7project\x64\Release\NppExport.dll" -FileName "$NPP_ExportPluginFileName"
        }

        if ($env:PLATFORM -eq "x64" -and $env:CONFIGURATION -eq "Debug") {
            Push-AppveyorArtifact "vs7project\x64\Debug\NppExport.dll" -FileName "$NPP_ExportPluginFileName"
        }

        if ($env:PLATFORM -eq "Win32" -and $env:CONFIGURATION -eq "Release") {
            Push-AppveyorArtifact "vs7project\Release\NppExport.dll" -FileName "$NPP_ExportPluginFileName"
        }

        if ($env:PLATFORM -eq "Win32" -and $env:CONFIGURATION -eq "Debug") {
            Push-AppveyorArtifact "vs7project\Debug\NppExport.dll" -FileName "$NPP_ExportPluginFileName"
        }

