version: 0.2.8.{build}
image: Visual Studio 2015


environment:
  matrix:
  - PlatformToolset: v140_xp
  - PlatformToolset: v120_xp

platform:
    - x64
    - Win32

configuration:
    - Release
    - Debug

install:
    - if "%platform%"=="x64" set archi=amd64
    - if "%platform%"=="Win32" set archi=x86
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" %archi%

build:
    parallel: true                  # enable MSBuild parallel builds
    verbosity: minimal

build_script:
    - cd "%APPVEYOR_BUILD_FOLDER%"\vs7project\
    - msbuild NppExport.vcxproj /p:configuration="%configuration%" /p:platform="%platform%" /p:PlatformToolset="%PlatformToolset%"

after_build:
    - cd "%APPVEYOR_BUILD_FOLDER%"
    - ps: >-

        if ($env:PLATFORM -eq "x64") {
            Push-AppveyorArtifact "vs7project\$env:PLATFORM\$env:CONFIGURATION\NppExport.dll" -FileName NppExport.dll
        }

        if ($env:PLATFORM -eq "Win32" ) {
            Push-AppveyorArtifact "vs7project\$env:CONFIGURATION\NppExport.dll" -FileName NppExport.dll
        }

        if ($($env:APPVEYOR_REPO_TAG) -eq "true" -and $env:CONFIGURATION -eq "Release" -and $env:PLATFORMTOOLSET -eq "v120_xp") {
            if($env:PLATFORM -eq "x64"){
            $ZipFileName = "NppExport_$($env:APPVEYOR_REPO_TAG_NAME)_x64.zip"
            7z a $ZipFileName vs7project\$env:PLATFORM\$env:CONFIGURATION\*.dll
            }
            if($env:PLATFORM -eq "Win32"){
            $ZipFileName = "NppExport_$($env:APPVEYOR_REPO_TAG_NAME)_x86.zip"
            7z a $ZipFileName vs7project\$env:CONFIGURATION\*.dll
            }
        }

artifacts:
  - path: NppExport_*.zip
    name: releases

deploy:
    provider: GitHub
    auth_token:
        secure: PhNXrhw03Z0rJZssX/UYyoIofw669wU1GBy/hGq+WJPCXd7mbxDu6Il32Rx0LBH6
    artifact: releases
    draft: false
    prerelease: false
    force_update: true
    on:
        appveyor_repo_tag: true
        PlatformToolset: v120_xp
        configuration: Release

